package com.memoprinter.eighty;

import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.*;import java.util.*;

public class SalesFeaturesActivity extends Activity{
 static final int BLUE=Color.rgb(37,99,235),TEXT=Color.rgb(15,23,42),MUTED=Color.rgb(100,116,139),BG=Color.rgb(246,248,252),WHITE=Color.WHITE,RED=Color.rgb(239,68,68);
 static final String SPP="00001101-0000-1000-8000-00805F9B34FB"; LinkedHashMap<String,Double> products=new LinkedHashMap<>(),today=new LinkedHashMap<>(); BluetoothSocket socket; LinearLayout root; Typeface bold,regular;
 public void onCreate(Bundle b){super.onCreate(b);bold=Typeface.DEFAULT_BOLD;regular=Typeface.DEFAULT;try{bold=Typeface.createFromAsset(getAssets(),"NotoSansBengali-Bold.ttf");regular=Typeface.createFromAsset(getAssets(),"NotoSansBengali-Regular.ttf");}catch(Exception e){}load();render();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(bg(WHITE,20));return c;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(WHITE);b.setBackground(bg(BLUE,16));return b;} Button light(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(BLUE);b.setBackground(bg(WHITE,16));return b;}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(WHITE,14));return e;}
 View gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
 ScrollView scroll(){ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(28));s.addView(c,new ScrollView.LayoutParams(-1,-1));root.addView(s,new LinearLayout.LayoutParams(-1,0,1));return s;}
 void shell(String title,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(WHITE);TextView back=tv("‹",36,TEXT);back.setGravity(Gravity.CENTER);bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(64)));back.setOnClickListener(v->finish());LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);TextView a=tv(title,21,TEXT);a.setTypeface(bold);tt.addView(a,new LinearLayout.LayoutParams(-1,dp(32)));tt.addView(tv(sub,12,MUTED),new LinearLayout.LayoutParams(-1,dp(22)));bar.addView(tt,new LinearLayout.LayoutParams(0,dp(64),1));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));setContentView(root);}
 String day(){return new SimpleDateFormat("yyyyMMdd",Locale.getDefault()).format(new Date());} String bn(String s){StringBuilder b=new StringBuilder();for(char c:s.toCharArray())b.append(c>='0'&&c<='9'?(char)('০'+c-'0'):c);return b.toString();} String fmt(double d){return Math.abs(d-Math.rint(d))<.0001?String.valueOf((long)Math.rint(d)):String.format(Locale.US,"%.2f",d);} double num(String s){if(s==null)return 0;StringBuilder b=new StringBuilder();for(char c:s.toCharArray()){if(c>='০'&&c<='৯')b.append((char)('0'+c-'০'));else if(c!=','&&c!=' '&&c!='৳')b.append(c);}try{return Double.parseDouble(b.toString());}catch(Exception e){return 0;}}
 void load(){try{JSONArray a=new JSONArray(getPreferences(0).getString("sales_products","[]"));for(int i=0;i<a.length();i++)products.put(a.getString(i),0.0);}catch(Exception e){}try{JSONObject o=new JSONObject(getPreferences(0).getString("sales_"+day(),"{}"));Iterator<String>it=o.keys();while(it.hasNext()){String k=it.next();today.put(k,o.getDouble(k));}}catch(Exception e){}}
 void save(){try{JSONArray a=new JSONArray();for(String k:products.keySet())a.put(k);JSONObject o=new JSONObject();for(String k:today.keySet())o.put(k,today.get(k));getPreferences(0).edit().putString("sales_products",a.toString()).putString("sales_"+day(),o.toString()).apply();}catch(Exception e){}}
 void render(){if("summary".equals(getIntent().getStringExtra("mode")))summary();else sales();}
 void sales(){shell("Sales Tracker","Product-wise daily quantity");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);LinearLayout intro=card();TextView h=tv("📈 Sales Tracker",20,TEXT);h.setTypeface(bold);intro.addView(h);intro.addView(tv("Product একবার add করুন। পরে quantity দিলেই আগের quantity-র সাথে যোগ হবে।",13,MUTED));c.addView(intro);c.addView(gap(10));Button add=btn("＋  Add Product");add.setOnClickListener(v->addProduct());c.addView(add);c.addView(gap(10));double total=0;
 if(products.isEmpty()){c.addView(card());}
 for(String n:new ArrayList<>(products.keySet())){double q=today.containsKey(n)?today.get(n):0;total+=q;LinearLayout r=card();LinearLayout top=new LinearLayout(this);TextView name=tv(n,17,TEXT);name.setTypeface(bold);top.addView(name,new LinearLayout.LayoutParams(0,dp(48),1));TextView qq=tv(bn(fmt(q))+" pcs",17,BLUE);qq.setGravity(Gravity.RIGHT);qq.setTypeface(bold);top.addView(qq,new LinearLayout.LayoutParams(dp(95),dp(48)));r.addView(top);LinearLayout bs=new LinearLayout(this);Button aq=btn("＋ Quantity");aq.setOnClickListener(v->addQty(n));Button del=light("Delete");del.setTextColor(RED);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete Product").setMessage(n+" মুছে ফেলবেন?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{products.remove(n);today.remove(n);save();sales();}).show());bs.addView(aq,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(dp(90),dp(48));dl.setMargins(dp(8),0,0,0);bs.addView(del,dl);r.addView(gap(6));r.addView(bs);c.addView(r);c.addView(gap(8));}
 LinearLayout tc=card();TextView gt=tv("আজকের মোট quantity: "+bn(fmt(total))+" pcs",19,TEXT);gt.setTypeface(bold);tc.addView(gt);c.addView(tc);}
 void addProduct(){EditText n=input("Product name");new AlertDialog.Builder(this).setTitle("Add Product").setView(n).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String x=n.getText().toString().trim();if(x.isEmpty())return;for(String k:products.keySet())if(k.equalsIgnoreCase(x)){toast("এই product আগে থেকেই আছে");return;}products.put(x,0.0);save();sales();}).show();}
 void addQty(String n){EditText q=input("Quantity — 10 / ১০");new AlertDialog.Builder(this).setTitle("Add Quantity").setView(q).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{double x=num(q.getText().toString());if(x<=0){toast("Quantity দিন");return;}today.put(n,(today.containsKey(n)?today.get(n):0)+x);save();sales();}).show();}
 LinkedHashMap<String,Double> summaryData(){LinkedHashMap<String,Double> m=new LinkedHashMap<>();try{JSONArray a=new JSONArray(getPreferences(0).getString("history","[]"));for(int i=0;i<a.length();i++){JSONArray q=a.getJSONObject(i).optJSONArray("items");if(q==null)continue;for(int j=0;j<q.length();j++){JSONObject x=q.getJSONObject(j);String n=x.optString("name").trim();if(n.isEmpty())continue;String old=null;for(String k:m.keySet())if(k.equalsIgnoreCase(n)){old=k;break;}double v=num(x.optString("qty"));if(old==null)m.put(n,v);else m.put(old,m.get(old)+v);}}}catch(Exception e){}return m;}
 void summary(){shell("Summary Printer","Automatic summary from Saved Memos");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);LinearLayout intro=card();TextView h=tv("🧾 Summary Printer",20,TEXT);h.setTypeface(bold);intro.addView(h);intro.addView(tv("Saved Memos-এর সব product automatically যোগ হবে।",13,MUTED));c.addView(intro);c.addView(gap(10));LinkedHashMap<String,Double> m=summaryData();if(m.isEmpty()){c.addView(card());return;}double total=0;LinearLayout list=card();for(Map.Entry<String,Double>e:m.entrySet()){total+=e.getValue();LinearLayout r=new LinearLayout(this);r.addView(tv(e.getKey(),16,TEXT),new LinearLayout.LayoutParams(0,dp(48),1));TextView q=tv(bn(fmt(e.getValue()))+" pcs",16,BLUE);q.setGravity(Gravity.RIGHT);q.setTypeface(bold);r.addView(q,new LinearLayout.LayoutParams(dp(105),dp(48)));list.addView(r);}TextView gt=tv("TOTAL  "+bn(fmt(total))+" pcs",19,TEXT);gt.setGravity(Gravity.RIGHT);gt.setTypeface(bold);list.addView(gt);c.addView(list);c.addView(gap(10));final double totalFinal=total;Button p=btn("🖨  Print Summary");p.setOnClickListener(v->selectPrinter(m,totalFinal));c.addView(p);}
 Bitmap makeBitmap(LinkedHashMap<String,Double>m,double total){int w=576,h=220+m.size()*54+120;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(WHITE);Paint p=new Paint(3);p.setColor(Color.BLACK);p.setTypeface(bold);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(34);c.drawText("MEMO PRINTER",w/2,55,p);p.setTextSize(27);c.drawText("Sales Summary",w/2,92,p);p.setTextSize(22);c.drawText(new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(new Date()),w/2,128,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(25);c.drawText("Product",24,176,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText("Qty",552,176,p);int y=228;p.setTypeface(regular);p.setTextSize(24);for(Map.Entry<String,Double>e:m.entrySet()){p.setTextAlign(Paint.Align.LEFT);c.drawText(e.getKey().length()>25?e.getKey().substring(0,25)+"…":e.getKey(),24,y,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText(bn(fmt(e.getValue()))+" pcs",552,y,p);y+=54;}p.setTypeface(bold);p.setTextSize(28);p.setTextAlign(Paint.Align.RIGHT);c.drawText("TOTAL  "+bn(fmt(total))+" pcs",552,y+18,p);return b;}
 void selectPrinter(LinkedHashMap<String,Double>m,double total){BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null||!a.isEnabled()){toast("Bluetooth চালু করুন");return;}if(Build.VERSION.SDK_INT>=31&&checkSelfPermission("android.permission.BLUETOOTH_CONNECT")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.BLUETOOTH_CONNECT"},20);return;}ArrayList<BluetoothDevice> ds=new ArrayList<>(a.getBondedDevices());if(ds.isEmpty()){toast("আগে Bluetooth settings থেকে printer pair করুন");return;}String[] n=new String[ds.size()];for(int i=0;i<ds.size();i++)n[i]=(ds.get(i).getName()==null?"Bluetooth device":ds.get(i).getName())+"\n"+ds.get(i).getAddress();new AlertDialog.Builder(this).setTitle("Select Printer").setItems(n,(d,w)->print(ds.get(w),m,total)).setNegativeButton("Cancel",null).show();}
 void print(BluetoothDevice d,LinkedHashMap<String,Double>m,double total){new Thread(()->{try{socket=d.createRfcommSocketToServiceRecord(UUID.fromString(SPP));socket.connect();OutputStream o=socket.getOutputStream();Bitmap b=makeBitmap(m,total);int wb=(b.getWidth()+7)/8,h=b.getHeight();o.write(new byte[]{0x1B,0x40,0x1D,0x76,0x30,0x00,(byte)wb,(byte)(wb>>8),(byte)h,(byte)(h>>8)});byte[] row=new byte[wb];for(int y=0;y<h;y++){Arrays.fill(row,(byte)0);for(int x=0;x<b.getWidth();x++){int col=b.getPixel(x,y);int g=(Color.red(col)*299+Color.green(col)*587+Color.blue(col)*114)/1000;if(g<170)row[x>>3]|=(byte)(128>>(x&7));}o.write(row);}o.write(new byte[]{0x1B,0x64,0x06,0x1D,0x56,0x00});o.flush();socket.close();runOnUiThread(()->toast("Summary print হয়েছে ✓"));}catch(Exception e){runOnUiThread(()->toast("Print failed — printer connection check করুন"));}}).start();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
