package com.memoprinter.eighty;

import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.*;import java.util.*;

public class SalesFeaturesActivity extends Activity{
 static final int BLUE=Color.rgb(37,99,235),TEXT=Color.rgb(15,23,42),MUTED=Color.rgb(100,116,139),BG=Color.rgb(246,248,252),WHITE=Color.WHITE,RED=Color.rgb(239,68,68);
 static final String SPP="00001101-0000-1000-8000-00805F9B34FB"; LinkedHashMap<String,Double> products=new LinkedHashMap<>(),today=new LinkedHashMap<>(); BluetoothSocket socket; LinearLayout root; Typeface bold,regular;
 public void onCreate(Bundle b){super.onCreate(b);bold=Typeface.DEFAULT_BOLD;regular=Typeface.DEFAULT;try{bold=Typeface.createFromAsset(getAssets(),"NotoSansBengali-Bold.ttf");regular=Typeface.createFromAsset(getAssets(),"NotoSansBengali-Regular.ttf");}catch(Exception e){}load();render();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(bg(WHITE,20));return c;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(WHITE);b.setBackground(bg(BLUE,16));return b;} Button light(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(BLUE);b.setBackground(bg(WHITE,16));return b;}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(WHITE,14));return e;}
 View gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
 ScrollView scroll(){ScrollView s=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(28));s.addView(c,new ScrollView.LayoutParams(-1,-1));root.addView(s,new LinearLayout.LayoutParams(-1,0,1));return s;}
 void shell(String title,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(WHITE);TextView back=tv("‹",36,TEXT);back.setGravity(Gravity.CENTER);bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(64)));back.setOnClickListener(v->finish());LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);TextView a=tv(title,21,TEXT);a.setTypeface(bold);tt.addView(a,new LinearLayout.LayoutParams(-1,dp(32)));tt.addView(tv(sub,12,MUTED),new LinearLayout.LayoutParams(-1,dp(22)));bar.addView(tt,new LinearLayout.LayoutParams(0,dp(64),1));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));setContentView(root);}
 String day(){return new SimpleDateFormat("yyyyMMdd",Locale.getDefault()).format(new Date());} String bn(String s){StringBuilder b=new StringBuilder();for(char c:s.toCharArray())b.append(c>='0'&&c<='9'?(char)('০'+c-'0'):c);return b.toString();} String fmt(double d){return Math.abs(d-Math.rint(d))<.0001?String.valueOf((long)Math.rint(d)):String.format(Locale.US,"%.2f",d);} double num(String s){if(s==null)return 0;StringBuilder b=new StringBuilder();for(char c:s.toCharArray()){if(c>='০'&&c<='৯')b.append((char)('0'+c-'০'));else if(c!=','&&c!=' '&&c!='৳')b.append(c);}String z=b.toString().trim();if(z.endsWith("কা"))z=z.substring(0,z.length()-2).trim();else{int slash=z.indexOf('/');if(slash>0)z=z.substring(0,slash).trim();}try{return Double.parseDouble(z);}catch(Exception e){return 0;}} void load(){try{JSONArray a=new JSONArray(getPreferences(0).getString("sales_products","[]"));for(int i=0;i<a.length();i++)products.put(a.getString(i),0.0);}catch(Exception e){}try{JSONObject o=new JSONObject(getPreferences(0).getString("sales_"+day(),"{}"));Iterator<String>it=o.keys();while(it.hasNext()){String k=it.next();today.put(k,o.getDouble(k));}}catch(Exception e){}}
 void save(){try{JSONArray a=new JSONArray();for(String k:products.keySet())a.put(k);JSONObject o=new JSONObject();for(String k:today.keySet())o.put(k,today.get(k));getPreferences(0).edit().putString("sales_products",a.toString()).putString("sales_"+day(),o.toString()).apply();}catch(Exception e){}}
 void render(){if("summary".equals(getIntent().getStringExtra("mode")))summaryDates();else sales();}
 void sales(){shell("Sales Tracker","Product-wise daily quantity");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);LinearLayout intro=card();TextView h=tv("📈 Sales Tracker",20,TEXT);h.setTypeface(bold);intro.addView(h);intro.addView(tv("Product একবার add করুন। পরে quantity দিলেই আগের quantity-র সাথে যোগ হবে।",13,MUTED));c.addView(intro);c.addView(gap(10));Button add=btn("＋  Add Product");add.setOnClickListener(v->addProduct());c.addView(add);c.addView(gap(10));double total=0;
 if(products.isEmpty()){c.addView(card());}
 for(String n:new ArrayList<>(products.keySet())){double q=today.containsKey(n)?today.get(n):0;total+=q;LinearLayout r=card();LinearLayout top=new LinearLayout(this);TextView name=tv(n,17,TEXT);name.setTypeface(bold);top.addView(name,new LinearLayout.LayoutParams(0,dp(48),1));TextView qq=tv(bn(fmt(q))+" pcs",17,BLUE);qq.setGravity(Gravity.RIGHT);qq.setTypeface(bold);top.addView(qq,new LinearLayout.LayoutParams(dp(95),dp(48)));r.addView(top);LinearLayout bs=new LinearLayout(this);Button aq=btn("＋ Quantity");aq.setOnClickListener(v->addQty(n));Button del=light("Delete");del.setTextColor(RED);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete Product").setMessage(n+" মুছে ফেলবেন?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{products.remove(n);today.remove(n);save();sales();}).show());bs.addView(aq,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(dp(90),dp(48));dl.setMargins(dp(8),0,0,0);bs.addView(del,dl);r.addView(gap(6));r.addView(bs);c.addView(r);c.addView(gap(8));}
 LinearLayout tc=card();TextView gt=tv("আজকের মোট quantity: "+bn(fmt(total))+" pcs",19,TEXT);gt.setTypeface(bold);tc.addView(gt);c.addView(tc);}
 void addProduct(){EditText n=input("Product name");new AlertDialog.Builder(this).setTitle("Add Product").setView(n).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String x=n.getText().toString().trim();if(x.isEmpty())return;for(String k:products.keySet())if(k.equalsIgnoreCase(x)){toast("এই product আগে থেকেই আছে");return;}products.put(x,0.0);save();sales();}).show();}
 void addQty(String n){EditText q=input("Quantity — 10 / ১০");new AlertDialog.Builder(this).setTitle("Add Quantity").setView(q).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{double x=num(q.getText().toString());if(x<=0){toast("Quantity দিন");return;}today.put(n,(today.containsKey(n)?today.get(n):0)+x);save();sales();}).show();}
 LinkedHashMap<String,Double> summaryData(String date){LinkedHashMap<String,Double> m=new LinkedHashMap<>();try{JSONArray a=mainHistory();for(int i=0;i<a.length();i++){JSONObject memo=a.getJSONObject(i);if(date!=null&&!date.equals(memo.optString("date")))continue;JSONArray q=memo.optJSONArray("items");if(q==null)continue;for(int j=0;j<q.length();j++){JSONObject x=q.getJSONObject(j);String n=x.optString("name").trim();if(n.isEmpty())continue;String old=null;for(String k:m.keySet())if(k.equalsIgnoreCase(n)){old=k;break;}double v=summaryQtyInPieces(n,x.optString("price"),x.optString("qty"));if(old==null)m.put(n,v);else m.put(old,m.get(old)+v);}}}catch(Exception ignored){}return m;}
 JSONArray mainHistory(){try{return new JSONArray(mainPrefs().getString("history","[]"));}catch(Exception e){return new JSONArray();}}
 android.content.SharedPreferences mainPrefs(){return getSharedPreferences("MainActivity",MODE_PRIVATE);}
 Double cartonPcsFor(String name,String priceText){
  try{
   JSONObject o=new JSONObject(mainPrefs().getString("carton_pcs","{}"));
   String q=name==null?"":name.trim();
   // 1) Exact product-name match.
   if(!q.isEmpty()){
    Iterator<String>it=o.keys();while(it.hasNext()){String k=it.next();if(k.trim().equalsIgnoreCase(q))return o.optDouble(k,0);}
   }
   // 2) Match product name against the saved default-price keys. This handles
   // English/Bangla display-name changes when the underlying default price is the same.
   double target=num(priceText);
   JSONObject pr=new JSONObject(mainPrefs().getString("prices","{}"));
   if(target>0){
    Double match=null; boolean ambiguous=false;
    Iterator<String>it=o.keys(); while(it.hasNext()){
     String k=it.next(); double cp=o.optDouble(k,0); double pv=pr.optDouble(k,Double.NaN);
     if(cp>0 && !Double.isNaN(pv) && Math.abs(pv-target)<0.0001){if(match==null)match=cp;else if(Math.abs(match-cp)>0.0001)ambiguous=true;}
    }
    if(match!=null && !ambiguous)return match;
   }
   // 3) If there is only one carton setting saved, use it. This is useful for
   // automatic English->Bangla product-name conversion and avoids losing 1কা.
   Iterator<String>it=o.keys(); String onlyKey=null; double onlyPcs=0; int count=0;
   while(it.hasNext()){String k=it.next();double cp=o.optDouble(k,0);if(cp>0){count++;onlyKey=k;onlyPcs=cp;}}
   if(count==1)return onlyPcs;
  }catch(Exception ignored){}
  return null;
 }
 double summaryQtyInPieces(String name,String priceText,String qty){if(qty==null)return 0;String z=qty.trim();boolean carton=z.matches("^[0-9০-৯]+(?:[.][0-9]+)?\\s*/\\s*[cC]$")||z.matches("^[0-9০-৯]+(?:[.][0-9]+)?\\s*কা$");double q=num(qty);if(!carton)return q;Double pcs=cartonPcsFor(name,priceText);return pcs==null?0:q*pcs;}
 ArrayList<String> historyDates(){ArrayList<String> d=new ArrayList<>();try{JSONArray a=mainHistory();for(int i=0;i<a.length();i++){String x=a.getJSONObject(i).optString("date").trim();if(!x.isEmpty()&&!d.contains(x))d.add(x);}}catch(Exception ignored){}Collections.sort(d,(a,b)->dateCompare(b,a));return d;}
 int dateCompare(String a,String b){try{return new SimpleDateFormat("dd/MM/yyyy",Locale.US).parse(a).compareTo(new SimpleDateFormat("dd/MM/yyyy",Locale.US).parse(b));}catch(Exception e){return a.compareTo(b);}}
 int memoCount(String date){int n=0;try{JSONArray a=mainHistory();for(int i=0;i<a.length();i++)if(date.equals(a.getJSONObject(i).optString("date")))n++;}catch(Exception ignored){}return n;}
 double dateTotal(String date){double t=0;try{JSONArray a=mainHistory();for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);if(date.equals(x.optString("date")))t+=x.optDouble("total",0);}}catch(Exception ignored){}return t;}
 String selectedSummaryDate(){String d=getIntent().getStringExtra("summaryDate");if(d!=null&&!d.trim().isEmpty())return d;ArrayList<String> ds=historyDates();return ds.isEmpty()?"":ds.get(0);}
 void summary(){String date=selectedSummaryDate();if(date.isEmpty()){shell("Summary Printer","Saved Memos থেকে product summary");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);LinearLayout box=card();TextView h=tv("🧾 Summary Printer",20,TEXT);h.setTypeface(bold);box.addView(h);box.addView(tv("Saved Memos নেই, তাই summary দেখানো যাচ্ছে না।",13,MUTED));c.addView(box);return;}summaryForDate(date);}
 void summaryForDate(String date){shell("Summary • "+date,bn(String.valueOf(memoCount(date)))+"টি Memo • Product-wise summary");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);
  LinearLayout head=card();TextView h=tv("🧾 "+date,20,TEXT);h.setTypeface(bold);head.addView(h);head.addView(tv("এই তারিখের সব Saved Memo থেকে product-wise quantity.",13,MUTED));c.addView(head);c.addView(gap(10));
  LinkedHashMap<String,Double> m=summaryData(date);
  if(m.isEmpty()){c.addView(tv("এই তারিখে কোনো product পাওয়া যায়নি",15,MUTED));return;}
  LinearLayout list=card();LinearLayout header=new LinearLayout(this);TextView hp=tv("Product",14,MUTED);hp.setTypeface(bold);TextView hq=tv("Total Qty",14,MUTED);hq.setGravity(Gravity.RIGHT);hq.setTypeface(bold);header.addView(hp,new LinearLayout.LayoutParams(0,dp(38),1));header.addView(hq,new LinearLayout.LayoutParams(dp(105),dp(38)));list.addView(header);
  double qtyTotal=0;for(Map.Entry<String,Double> e:m.entrySet()){qtyTotal+=e.getValue();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView n=tv(e.getKey(),16,TEXT);n.setTypeface(bold);TextView q=tv(bn(fmt(e.getValue()))+" pcs",16,BLUE);q.setGravity(Gravity.RIGHT);q.setTypeface(bold);r.addView(n,new LinearLayout.LayoutParams(0,dp(52),1));r.addView(q,new LinearLayout.LayoutParams(dp(105),dp(52)));list.addView(r);}
  TextView qt=tv("Total Quantity: "+bn(fmt(qtyTotal))+" pcs",16,TEXT);qt.setGravity(Gravity.RIGHT);qt.setTypeface(bold);list.addView(qt);c.addView(list);c.addView(gap(10));
  final double summaryTotalQty=qtyTotal;
  Button printSummary=btn("🖨  Print Summary");
  c.addView(printSummary,new LinearLayout.LayoutParams(-1,dp(52)));
  c.addView(gap(8));
  Button back=light("‹  All Dates");
  c.addView(back,new LinearLayout.LayoutParams(-1,dp(52)));
  printSummary.setOnClickListener(v->selectPrinter(m,summaryTotalQty,date));
  back.setOnClickListener(v->{getIntent().putExtra("summaryDate","");summaryDates();});
 }
 void summaryDates(){shell("Summary Printer","তারিখ select করুন → Generate Summary");ScrollView sv=scroll();LinearLayout c=(LinearLayout)sv.getChildAt(0);LinearLayout intro=card();TextView h=tv("🧾 Summary Printer",20,TEXT);h.setTypeface(bold);intro.addView(h);intro.addView(tv("একটি date select করে Generate Summary চাপলে ওই দিনের সব Saved Memo থেকে product-wise quantity বের হবে।",13,MUTED));c.addView(intro);c.addView(gap(10));ArrayList<String> ds=historyDates();if(ds.isEmpty()){c.addView(tv("Saved Memos নেই",15,MUTED));return;}final Spinner spinner=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ds);spinner.setAdapter(adapter);LinearLayout pick=card();pick.addView(tv("Date select করুন",14,MUTED));pick.addView(spinner,new LinearLayout.LayoutParams(-1,dp(52)));c.addView(pick);c.addView(gap(12));Button generate=btn("🧾  Generate Summary");generate.setOnClickListener(v->{String selected=(String)spinner.getSelectedItem();if(selected!=null&&!selected.trim().isEmpty())summaryForDate(selected);});c.addView(generate);c.addView(gap(12));LinearLayout note=card();note.addView(tv("Summary-তে শুধু Product-wise Total Quantity থাকবে। Total Amount থাকবে না.",13,MUTED));c.addView(note);}
 Bitmap makeBitmap(LinkedHashMap<String,Double>m,double total,String date){int w=576,h=220+m.size()*54+120;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(WHITE);Paint p=new Paint(3);p.setColor(Color.BLACK);p.setTypeface(bold);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(34);c.drawText("MEMO PRINTER",w/2,55,p);p.setTextSize(27);c.drawText("Sales Summary",w/2,92,p);p.setTextSize(22);c.drawText((date==null?"":date)+"  •  "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()),w/2,128,p);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(25);c.drawText("Product",24,176,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText("Qty",552,176,p);int y=228;p.setTypeface(regular);p.setTextSize(24);for(Map.Entry<String,Double>e:m.entrySet()){p.setTextAlign(Paint.Align.LEFT);c.drawText(e.getKey().length()>25?e.getKey().substring(0,25)+"…":e.getKey(),24,y,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText(bn(fmt(e.getValue()))+" pcs",552,y,p);y+=54;}p.setTypeface(bold);p.setTextSize(28);p.setTextAlign(Paint.Align.RIGHT);c.drawText("TOTAL  "+bn(fmt(total))+" pcs",552,y+18,p);return b;}
 void selectPrinter(LinkedHashMap<String,Double>m,double total){selectPrinter(m,total,"Summary");}
 void selectPrinter(LinkedHashMap<String,Double>m,double total,String date){BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null||!a.isEnabled()){toast("Bluetooth চালু করুন");return;}if(Build.VERSION.SDK_INT>=31&&checkSelfPermission("android.permission.BLUETOOTH_CONNECT")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.BLUETOOTH_CONNECT"},20);return;}String savedMac=mainPrefs().getString("printerMac","");String savedName=mainPrefs().getString("printerName","");ArrayList<BluetoothDevice> ds=new ArrayList<>();try{for(BluetoothDevice d:a.getBondedDevices())ds.add(d);}catch(Exception ignored){}if(ds.isEmpty()){toast("আগে Bluetooth settings থেকে printer pair করুন");return;}String[] n=new String[ds.size()];for(int i=0;i<ds.size();i++)n[i]=(ds.get(i).getName()==null?"Bluetooth device":ds.get(i).getName())+"\\n"+ds.get(i).getAddress();new AlertDialog.Builder(this).setTitle(savedName.isEmpty()?"Select Printer":"Select Printer • "+savedName).setItems(n,(d,w)->print(ds.get(w),m,total,date)).setNegativeButton("Cancel",null).show();}
 void print(BluetoothDevice d,LinkedHashMap<String,Double>m,double total,String date){new Thread(()->{try{socket=d.createRfcommSocketToServiceRecord(UUID.fromString(SPP));socket.connect();OutputStream o=socket.getOutputStream();Bitmap b=makeBitmap(m,total,date);int wb=(b.getWidth()+7)/8,h=b.getHeight();o.write(new byte[]{0x1B,0x40,0x1D,0x76,0x30,0x00,(byte)wb,(byte)(wb>>8),(byte)h,(byte)(h>>8)});byte[] row=new byte[wb];for(int y=0;y<h;y++){Arrays.fill(row,(byte)0);for(int x=0;x<b.getWidth();x++){int col=b.getPixel(x,y);int g=(Color.red(col)*299+Color.green(col)*587+Color.blue(col)*114)/1000;if(g<170)row[x>>3]|=(byte)(128>>(x&7));}o.write(row);}o.write(new byte[]{0x1B,0x64,0x06,0x1D,0x56,0x00});o.flush();socket.close();runOnUiThread(()->toast("Summary print হয়েছে ✓"));}catch(Exception e){runOnUiThread(()->toast("Print failed — printer connection check করুন"));}}).start();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
